<a href="https://colab.research.google.com/github/Khushibung05/TEKWORKS/blob/main/farms.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import numpy as np
farmA=np.array([[10,12,11],[9,11,10],[12,13,14],[8,7,9]])
farmB=np.array([[20,19,21],[18,20,19],[22,23,21],[17,18,16]])
farmC=np.array([[15,16,14],[14,13,15],[16,17,18],[12,11,13]])
production_all=np.array([farmA,farmB,farmC])
print("production:",production_all)
print("shape:",production_all.shape)
print("size:",production_all.size)
print("dtype:",production_all.dtype)
print("ndim:",production_all.ndim)
#Use aggregation ufuncs to compute the total energy per farm (sum across panels & hours) → total_per_farm (shape (3,)).
total_per_farm=np.sum(production_all,axis=(1,2))
print("total energy per farm",total_per_farm)
#Compute mean, std, and var per farm.
print("mean per farm:",np.mean(production_all,axis=(1,2)))
print("std per farm:",np.std(production_all,axis=(1,2)))
print("var per farm:",np.var(production_all,axis=(1,2)))
hour_weights=np.array([0.5, 1.0, 0.75])
weighted_per_panel=np.dot(production_all,hour_weights)
print(weighted_per_panel)
#The operator notices a fixed calibration offset of +0.5 kWh for all panels in Farm B. Use broadcasting to add this offset to Farm B data inside production_all (without recreating whole array manually)
production_all[1,:,:]=production_all[1,:,:]+0.5
print(production_all)
#Compute a normalized version where you: subtract the per-farm mean (use broadcasting),divide by the per-farm std (broadcasting) — i.e., z-score normalize each farm's panel-hour readings.
mean_per_farm=np.mean(production_all,axis=(1,2),keepdims=True)
std_per_farm=np.std(production_all,axis=(1,2),keepdims=True)
normalized_per_farm=(production_all-mean_per_farm)/std_per_farm
print(normalized_per_farm)
#Use broadcasting to compute a (3,4) array panel_totals_per_farm = total per panel (sum across hours for each panel)
panel_totals_per_farm=np.sum(production_all,axis=2)
print(panel_totals_per_farm)
#boolean needs_maintenance saying True if any panel in that farm has total < 40. Use np.min, np.max, np.any, np.all
needs_maintenance=np.any(panel_totals_per_farm<40,axis=1)
print(needs_maintenance)
#overall_total (sum of all farms)
overall_total=np.sum(production_all)
print(overall_total)


production: [[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
shape: (3, 4, 3)
size: 36
dtype: int64
ndim: 3
total energy per farm [126 234 174]
mean per farm: [10.5 19.5 14.5]
std per farm: [1.97905701 1.97905701 1.97905701]
var per farm: [3.91666667 3.91666667 3.91666667]
[[25.25 23.   29.5  17.75]
 [44.75 43.25 49.75 38.5 ]
 [34.   31.25 38.5  26.75]]
[[[10 12 11]
  [ 9 11 10]
  [12 13 14]
  [ 8  7  9]]

 [[20 19 21]
  [18 20 19]
  [22 23 21]
  [17 18 16]]

 [[15 16 14]
  [14 13 15]
  [16 17 18]
  [12 11 13]]]
[[[-0.25264558  0.75793673  0.25264558]
  [-0.75793673  0.25264558 -0.25264558]
  [ 0.75793673  1.26322788  1.76851903]
  [-1.26322788 -1.76851903 -0.75793673]]

 [[ 0.25264558 -0.25264558  0.75793673]
  [-0.75793673  0.25264558 -0.25264558]
  [ 1.26322788  1.76851903  0.75793673]
  [-1.26322788 -0.75793673 -1.76851903]]

 [[ 0.25264558  0.75793673 -0.25264558]
  [-0