<a href="https://colab.research.google.com/github/Khushibung05/TEKWORKS/blob/main/finalTask.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [36]:
import numpy as np
a=np.arange(10,51)
print(a)
r=np.random.random((3,3))
print(r)
print(f"shape:{r.shape}")
print(f"size:{r.size}")
print(f"dimension:{r.ndim}")
print(f"datatype:{r.dtype}")
#Add 5 to every element of a 1D array.
print("a+5:",a+5)
#Multiply two 2D arrays element-wise.
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print(f"m1+m2:{m1*m2}")
#Create a 5x5 array of integers from 1 to 25. Extract:
#The first row.
#The last column.
#A subarray of the first three rows and first two columns.
index_slice=np.arange(1,26)
mat=index_slice.reshape(5,5)
print("5x5 2D array:",mat)
print("first row:",mat[0])
print("last column:",mat[:,-1])
print("sub array:",mat[0:3,0:2])
#Create a 10-element array of random integers between 10 and 100. Find:
#The maximum value.
#The minimum value.
#The mean and standard deviation.
arr10=np.random.randint(10,100,10)
print("random integers in 10-100",arr10)
print("max:",np.max(arr10))
print("min:",np.min(arr10))
print("mean:",np.mean(arr10))
print("std:",np.std(arr10))
#Reshaping:Convert a 1D array of numbers from 1 to 12 into a 3x4 matrix.
a1_12=np.arange(1,13)
converted=a1_12.reshape(3,4)
print("reshape:",converted)
#Broadcasting:Create a 3x3 matrix of ones. Add a 1D array [1, 2, 3] to each row.
ones=np.ones((3,3))
arr1=[1,2,3]
print("broadcasted",ones+arr1)
#Filtering:Create a 1D array of random integers between 1 and 50. Extract all elements that are divisible by 5.
a1_50=np.random.randint(1,50,10)
print("array:",a1_50)
print("ele divisible by 5:",a1_50[a1_50%5==0])
#Matrix Multiplication:Create two 2x2 matrices and perform matrix multiplication.
m1=np.array([[1,2],[3,4]])
m2=np.array([[5,6],[7,8]])
print("matrix multiplication:",np.dot(m1,m2))
#Advanced Indexing:Given a 4x4 array, use fancy indexing to extract the diagonal elements.
arr=np.arange(1,17).reshape(4,4)
print(arr)
diag=arr.diagonal()
print("diagonal elements:",diag)
#diag=arr[np.arange(4),np.arange(4)]
diag=arr[[0,1,2,3],[0,1,2,3]]
print(diag)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[[0.79288505 0.28687766 0.63553501]
 [0.55027271 0.6806896  0.37982572]
 [0.79315403 0.67356175 0.82773401]]
shape:(3, 3)
size:9
dimension:2
datatype:float64
a+5: [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38
 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55]
m1+m2:[[ 5 12]
 [21 32]]
5x5 2D array: [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
first row: [1 2 3 4 5]
last column: [ 5 10 15 20 25]
sub array: [[ 1  2]
 [ 6  7]
 [11 12]]
random integers in 10-100 [87 86 87 56 31 48 88 59 67 58]
max: 88
min: 31
mean: 66.7
std: 18.7725863961256
reshape: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
broadcasted [[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
array: [ 5 21 22 49 15 11 11 10 19 26]
ele divisible by 5: [ 5 15 10]
matrix multiplication: [[19 22]
 [43 50]]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11