<a href="https://colab.research.google.com/github/Khushibung05/TEKWORKS/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [20]:
b=np.array(42)
a=np.array([[1,2,3],[1,2,3]])
print(a.ndim)
print(a.shape)
print(a.size)
print(a.dtype)
zeros=np.zeros((3,2))
print(zeros)
ones=np.ones((2,3,3))
print(ones)
identity=np.eye(3)
print(identity)
range_arr=np.arange(0,10,2)
print(range_arr)
rand=np.random.random((2,3,3))
print(rand)

2
(2, 3)
6
int64
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[[[0.86195637 0.27097825 0.15239552]
  [0.58237492 0.66955796 0.52524417]
  [0.18850505 0.29377482 0.71757042]]

 [[0.08295089 0.86862205 0.93137938]
  [0.03714685 0.63349979 0.04280622]
  [0.96406573 0.95279921 0.69447155]]]


In [14]:
temp_data=np.array([[27,25,20],[24,26,23]])
print(temp_data)
print(temp_data.ndim)
print(temp_data.shape)
print(temp_data.size)
print(temp_data.dtype)
GH3=np.array([21,23,22])
updated_temp_data = np.vstack([temp_data, GH3])
print(updated_temp_data)
sensor_error_flags=np.zeros((2,3))
greenhouse_identity=np.eye(3)
print(sensor_error_flags)
print(greenhouse_identity)


[[27 25 20]
 [24 26 23]]
2
(2, 3)
6
int64
[[27 25 20]
 [24 26 23]
 [21 23 22]]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#indexing
a=np.array([[1,2,3],[4,5,6]])
print(a[0,1])
print(a[1,-1])
#slicing
print(a[0:,1:])
print(a[0:1])
print(a[1:3,0:2])

2
6
[[2 3]
 [5 6]]
[[1 2 3]]
[[4 5]]


In [30]:
#rows=no. of shipments of each fruit type
#cols=mon,tue,wed,thurs,fri,sat,sun
shipments=np.array([[50,60,55,70,65,80,90],[40,45,58,90,55,70,75]])
#no. of apples shipped on wednesday
print(shipments[0,2])
#no. of oranghes shipped on sunday
print(shipments[1,6])
#Extract all the weekday shipments (Mon–Fri) for all fruits
print(shipments[:,0:5])#all rows
#Extract only the weekend shipments (Sat & Sun).
print(shipments[:,5:7])
#Extract the shipments of Apples from Wednesday to Saturday.
print(shipments[0:1,2:6])
#Replace the Saturday shipment of Apples (currently 80) with 100 using indexing.
shipments[0,5]=100
print(shipments)


55
75
[[50 60 55 70 65]
 [40 45 58 90 55]]
[[80 90]
 [70 75]]
[[55 70 65 80]]
[[ 50  60  55  70  65 100  90]
 [ 40  45  58  90  55  70  75]]


In [33]:
a=np.array([1,2,3])
b=np.array([4,5,6])
#arithmetic element wise operations
print(a+b)#ewise add
print(a*b)#ewise mul
print(a*2)#scalar
print(a-b)
print(a/b)
print(b//a)
print(a%b)


[5 7 9]
[ 4 10 18]
[2 4 6]
[-3 -3 -3]
[0.25 0.4  0.5 ]
[4 2 2]
[1 2 3]


In [37]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a+b)#ewise add
print(a*b)#ewise mul
print(a*2)#scalar
print(a-b)
print(a/b)
print("floor div:",b//a)
print(a%b)
#matrix oprn fns
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))
print(np.dot(a,b))#shapes must be compatible for product

[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
floor div: [[4 2 2]
 [1 1 1]
 [0 0 0]]
[[1 2 3]
 [4 5 6]
 [0 0 0]]
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]
[[1 2 3]
 [4 5 6]
 [0 0 0]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In [38]:
#broadcasting-elewise
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[4,5,6],[7,8,9]])
c=4
print(a+b)#ewise add
print(a*b)#ewise mul
print(a+c)

[[ 5  7  9]
 [11 13 15]]
[[ 4 10 18]
 [28 40 54]]
[[ 5  6  7]
 [ 8  9 10]]


In [ ]:
#ufuncs
x=np.array([[1,2.4,3.6],[4,5,6],[7,8.5,9]])
y=np.array([[4,5,6],[7.8,8.3,9],[1,2.4,3]])
# Arithmetic ufuncs
#Operate element-wise on arrays.
np.add(x, y)
np.subtract(x, y)
np.multiply(x, y)
np.divide(x, y)
np.power(x, y)
np.mod(x, y)
# 2. Exponential and Logarithmic ufuncs
#(You already covered these)
np.exp(x)
np.log(x)
np.log10(x)
np.log2(x)
np.expm1(x)    # exp(x) - 1
# 3. Trigonometric ufuncs
np.sin(x)
np.cos(x)
np.tan(x)
np.arcsin(x)
np.arccos(x)
np.arctan(x)
np.degrees(x)
np.radians(x)
# 4. Rounding ufuncs
np.round(x)
np.floor(x)
np.ceil(x)
np.trunc(x)
# 5. Statistical ufuncs
#(Operate along an axis or entire array)
np.min(x)
np.max(x)
np.mean(x)
np.std(x)
np.var(x)
np.sum(x)
np.prod(x)
# 6. Logical ufuncs
np.logical_and(x, y)
np.logical_or(x, y)
np.logical_not(x)
np.logical_xor(x, y)
print(" 7. Comparison ufuncs")
#(Return Boolean arrays)
np.greater(x, y)
np.less(x, y)
np.equal(x, y)
np.not_equal(x, y)
np.greater_equal(x, y)
np.less_equal(x, y)
print(" 8. Bitwise ufuncs")
#(Operate on integers)
np.bitwise_and(x, y)
np.bitwise_or(x, y)
np.bitwise_xor(x, y)
np.invert(x)

In [55]:
#reshaping
a=np.arange(1,10)
print(a)
b=a.reshape(3,3)
print(b)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [63]:
#stacking and splitting
a=np.array([1,2])
b=np.array([3,4])
print(np.vstack((a,b)))
print(np.hstack((a,b)))
c=np.array([1,2,3,4,5,6])
print(np.array_split(c,3))
print(np.array_split(c,7))

[[1 2]
 [3 4]]
[1 2 3 4]
[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1]), array([2]), array([3]), array([4]), array([5]), array([6]), array([], dtype=int64)]


In [64]:
#advanced indexing
arr=np.array([1,2,3,4,5])
print(arr[arr>3])
ind=[0,2]
print(arr[ind])

[4 5]
[1 3]


In [65]:
#view and copy
arr=np.array([1,2,3])
view=arr.view()
view[0]=10
print(arr)
arr=np.array([1,2,3])
copy=arr.copy()
copy[0]=10
print(arr)

[10  2  3]
[1 2 3]


In [67]:
#saving and loading
arr=np.array([1,2,3])
np.save('array.npy',arr)
loaded_arr=np.load('array.npy')
print(loaded_arr)

[1 2 3]
